#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - python3
  - python3-pip
  - python3-venv

runcmd:
  - wget -O /tmp/package.deb https://github.com/opentofu/opentofu/releases/download/v1.6.2/tofu_1.6.2_amd64.deb && sudo dpkg -i /tmp/package.deb && rm /tmp/package.deb
